### ISSUE TITLE
ctf_sec - Blocklisted recipient or address(0) force operator to waste gas when filling the sell order or filling the cancel order

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-dinari-judging#57]
ctf_sec

medium

# Blocklisted recipient or address(0) force operator to waste gas when filling the sell order or filling the cancel order

## Summary

Blocklisted recipient or address(0) force operator to waste gas when filling the order

## Vulnerability Detail

When creating the order, the asset token and payment token is whitelited and validated

```solidity
   function requestOrder(OrderRequest calldata orderRequest, bytes32 salt) public nonReentrant whenOrdersNotPaused {
        // Reject spam orders
        if (orderRequest.quantityIn == 0) revert ZeroValue();
        // Check for whitelisted tokens
        _checkRole(ASSETTOKEN_ROLE, orderRequest.assetToken);
        _checkRole(PAYMENTTOKEN_ROLE, orderRequest.paymentToken);
        bytes32 orderId = getOrderIdFromOrderRequest(orderRequest, salt);
        // Order must not already exist
        if (_orders[orderId].remainingOrder > 0) revert DuplicateOrder();

        // Get order from request and move tokens
        Order memory order = _requestOrderAccounting(orderRequest, orderId);

        // Send order to bridge
        emit OrderRequested(orderId, order.recipient, order, salt);

        // Initialize order state
        uint256 orderAmount = order.sell ? order.assetTokenQuantity : order.paymentTokenQuantity;
        _orders[orderId] = OrderState({requester: msg.sender, remainingOrder: orderAmount, received: 0});
        _numOpenOrders++;
    }

```

but the order.recipient is never validated

the payment token can be USDC and support blocklist, the user can set order.recipient to a blocked token address

the user can also set the recipient address to address(0)

then later when the operator want to fill in the order

the operator are force to waste gas and the order filling transaction keep reverting because the recipient cannot receive the payment token in Sell Order

https://github.com/sherlock-audit/2023-06-dinari/blob/4851cb7ebc86a7bc26b8d0d399a7dd7f9520f393/sbt-contracts/src/issuer/SellOrderProcessor.sol#L171

```solidity
    function _distributeProceeds(address paymentToken, address recipient, uint256 totalReceived, uint256 feesEarned)
        private
    {
        // Check if accumulated fees are larger than total received
        uint256 proceeds = 0;
        uint256 collection = 0;
        if (totalReceived > feesEarned) {
            // Take fees from total received before distributing
            proceeds = totalReceived - feesEarned;
            collection = feesEarned;
        } else {
            // If accumulated fees are larger than total received, then no proceeds go to recipient
            collection = totalReceived;
        }

        // Transfer proceeds to recipient
        if (proceeds > 0) {
            IERC20(paymentToken).safeTransfer(recipient, proceeds);
        }
        // Transfer fees to treasury
        if (collection > 0) {
            IERC20(paymentToken).safeTransfer(treasury, collection);
        }
    }
```

In BuyOrder

User can send a tiny amount of payment and then call cancel order

the operator is expected to help user cancel order, but when he doing so, the gas is wasted because the transaction would keep reverting because the recipient address is blocklisted or address(0)

[here](https://github.com/sherlock-audit/2023-06-dinari/blob/4851cb7ebc86a7bc26b8d0d399a7dd7f9520f393/sbt-contracts/src/issuer/BuyOrderIssuer.sol#L214)

## Impact

Blocklisted recipient or address(0) force operator to waste gas when filling the sell order or filling the cancel order

## Code Snippet

https://github.com/sherlock-audit/2023-06-dinari/blob/4851cb7ebc86a7bc26b8d0d399a7dd7f9520f393/sbt-contracts/src/issuer/BuyOrderIssuer.sol#L214

https://github.com/sherlock-audit/2023-06-dinari/blob/4851cb7ebc86a7bc26b8d0d399a7dd7f9520f393/sbt-contracts/src/issuer/SellOrderProcessor.sol#L171

## Tool used

Manual Review

## Recommendation

We recommend the protocol validate the recipient address to not let user set a blocklisted address or address(0)

**Comment by 0xDE-GEN** [comment]
Escalate

I think this issue is out of scope.

The issue states that the operator could lose as much as the cost of gas.

However, this may not be a loss at all depending on the implementation of the operator script (e.g. checking if the transaction will be reverted, checking if the recipient is blacklisted, etc.)

Also, the argument that the OPERATOR could lose money by buying stocks for order, is not a problem if check the recipient before trading.

If we need to make assumptions about the logic of the off-chain, I think this is out of scope.

**Comment by sherlock-admin** [comment]
> Escalate
> 
> I think this issue is out of scope.
> 
> The issue states that the operator could lose as much as the cost of gas.
> 
> However, this may not be a loss at all depending on the implementation of the operator script (e.g. checking if the transaction will be reverted, checking if the recipient is blacklisted, etc.)
> 
> Also, the argument that the OPERATOR could lose money by buying stocks for order, is not a problem if check the recipient before trading.
> 
> If we need to make assumptions about the logic of the off-chain, I think this is out of scope.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Shogoki** [comment]
I think it is mainly because of the loss the operator makes., as i stated in my report #46.

According to the sponsor, the operator automatically tries ti execute the trade. If the following call to fulfill fails, the operator has to take a loss.
![image](https://github.com/sherlock-audit/2023-06-dinari-judging/assets/1040321/0f759017-a05b-4689-902b-d317ab9c82b9)
![image](https://github.com/sherlock-audit/2023-06-dinari-judging/assets/1040321/0fb18665-da6a-4365-95a2-0b724d89153b)

**Comment by 0xDE-GEN** [comment]
I agree that it could cause gas loss if implemented that way. 

However, information confirmed via DM should not be taken into account.
> Discord messages or DM screenshots are not considered sources of truth while judging an issue/escalation especially if they are conflicting with the contest README. (https://docs.sherlock.xyz/audits/judging/judging#some-standards-observed)

I think operator's implementation is out of scope.

**Comment by Oot2k** [comment]
Agree that this more low. The operator implementation is out of scope.

**Comment by Shogoki** [comment]
Hmm. Agree that operator implementation is out of scope, that is why we have to expect it is working as described. The flaw itself is not in the operator implementation, but in the smart contract, i think.

**Comment by ctf-sec** [comment]
> Hmm. Agree that operator implementation is out of scope, that is why we have to expect it is working as described. The flaw itself is not in the operator implementation, but in the smart contract, i think.

We have to make some assumption about the operator behavior, a reasonable assumption is the operator trying to fill the order or cancel the order with reaonsable order size.

Agree, the flaw is the smart contract will push the fund out to receiver which keeps the transaction keep reverts

Issue like this in past is even considered as high severity.

https://github.com/sherlock-audit/2023-02-gmx-judging/issues/141

**Comment by 0xDE-GEN** [comment]
What constitutes a resonable assumption may be different for different people. 

One person might think it's reasonable to keep trying a transaction that reverts, while another might think it's reasonable to confirm the receiver is not blocklist and try the transaction.
(Personally, I think not retry if it reverts is reasonable method, because there's nothing time-dependent about it)

Someone who thinks it's reasonable not to send a transaction if it reverts might think it's not an issue. 
So, I think a vulnerability that requires you to make these assumptions is out of scope.

**Comment by ctf-sec** [comment]
![image](https://github.com/sherlock-audit/2023-06-dinari-judging/assets/114844362/bf4bdf85-5410-451b-9369-1743e0e0d6cb)

there is no mention about the receiver input validation :)

**Comment by 0xDE-GEN** [comment]
The point of my argument is not that the issue is invalid because there is input validation.

I agree that the current implementation can result in a loss of protocol. However, when the contest was going on, the other Watsons would have made their own assumptions, not knowing how the operator would be implemented.

I'm saying that any vulnerabilities that might come from those off-chain assumptions are out of scope.

As I said, in someone's assumptions, the vulnerability may not have caused a loss of protocol (even if it's not input validation, if it's a transaction with revert, don't do it, etc).

In fact, the vulnerability is only valid under the assumption that the operator "will fill repeatedly even if it reverts". The protocol design does allow the operator to use N gas per 1 order.

**Comment by Shogoki** [comment]
> However, when the contest was going on, the other Watsons would have made their own assumptions, not knowing how the operator would be implemented.

To validate the assumption everybody can ask the sponsor, like i did. 


> In fact, the vulnerability is only valid under the assumption that the operator "will fill repeatedly even if it reverts". The protocol design does allow the operator to use N gas per 1 order.

This holds true to the gas, but not to the loss from the trade.. It is just reasonable to assume the operator executes the trade, when it receives the order from the bridge..

**Comment by 0xDE-GEN** [comment]
Even if it was announced how the operator works, I think the impact of the issue is too low.

If the protocol bought the wrong shares, they would be able to sell them back to their broker immediately, and I doubt that would have enough impact to qualify as Medium.

Moreover, the attacker would probably order a small quantity since the order cannot be canceled, and the loss from the trade would be very small.

**Comment by 0xarshia** [comment]
In this scenario user will also lose payment tokens:
user creates a request order with USDT for example, and then the recipient address gets blacklisted in USDT. in this situation, OPERATOR can't cancel the order. So if order is not fillable or needs to be canceled for some reason, the _cancelOrderAccounting() function will revert. payment tokens will be stuck because the OPERATOR cant fill or cancel order.

So basically it's not about only just wasting gas. This issue is a valid medium.

**Comment by jaketimothy** [comment]
Fixed in 
- https://github.com/dinaricrypto/sbt-contracts/pull/116

**Comment by hrishibhat** [comment]
Result:
Low 
Has duplicates
This issue and its duplicates have similar behavior with #55 and with all the discussion in the comments and further discussion with the Sponsor considering this issue a valid low. Losing gas for operator is not a valid issue. 
And incase of a lock refer :https://github.com/sherlock-audit/2023-06-dinari-judging/issues/55#issuecomment-1662046155

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [dot-pengun](https://github.com/sherlock-audit/2023-06-dinari-judging/issues/57/#issuecomment-1633722335): accepted
