### ISSUE TITLE
toshii - Malicious user can prevent treasury from getting fees in BuyOrderIssuer

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-dinari-judging#78]
toshii

high

# Malicious user can prevent treasury from getting fees in BuyOrderIssuer

## Summary

A malicious user can craft a buy order using the BuyOrderIssuer in a certain way which prevents the treasury from receiving fees at a low cost to the user.

## Vulnerability Detail

Both the BuyOrderIssuer and SellOrderProcessor are implemented similarly (in terms of fees distribution) in that the fees meant for the treasury are only sent when the entire order is fulfilled, or the order is partially fulfilled and the order is cancelled. The difference however, is that in SellOrderProcessor, the total `receivedAmount` of tokens will only be sent to the user for selling their `assetToken` at the same time as when the fees are sent to the treasury.

In BuyOrderIssuer, when an order is partially fulfilled, the `receivedAmount` of the `assetToken` is still minted to the user (meaning there is no waiting for the order to be completely fulfilled, or canceled). This can be seen with the implementation of `_fillOrderAccounting`:
```solidity
function _fillOrderAccounting(
    ...
) internal virtual override {
    // Calculate fees and mint asset
    _fillBuyOrder(orderRequest, orderId, orderState, fillAmount, receivedAmount);

    // Claim payment
    IERC20(orderRequest.paymentToken).safeTransfer(msg.sender, fillAmount);
}
```
where `_fillBuyOrder` is defined as:
```solidity
function _fillBuyOrder(
    ...
) internal virtual {
    ...
    // Mint asset
    IMintBurn(orderRequest.assetToken).mint(orderRequest.recipient, receivedAmount);
}
```
This means that a malicious user can craft a buy order which will never be complete (so fees won't be sent to the treasury), yet will allow them to maximize their `receivedAmount` of the `assetToken`. Consider a simplified scenario where the market price for an `assetToken` is 100e18 USDC. Let's say the malicious user wants to craft a buy order where they want 5 of these tokens. Let's assume in this case, the total fees (fixed + variable) is 25e18 USDC. The user will then create a buy order in which they set 526e18 USDC as the `quantityIn`. This will result in 1e18 USDC to remain as the `orderState.remainingOrder` after the 5 tokens are purchased, meaning the order cannot be closed. This then means that the fees are never sent to the treasury, whereas the user has still received all their desired tokens.

## Impact

The treasury can be cheated out of receiving fees associated with performing a buy order as defined in the BuyOrderIssuer contract.

## Code Snippet

Referenced lines of code:
https://github.com/sherlock-audit/2023-06-dinari/blob/main/sbt-contracts/src/issuer/BuyOrderIssuer.sol#L161-L190
https://github.com/sherlock-audit/2023-06-dinari/blob/main/sbt-contracts/src/issuer/BuyOrderIssuer.sol#L146-L158

## Tool used

Manual Review

## Recommendation

During each call to `_fillBuyOrder`, the current `_feeState[orderId].feesEarned` should be sent to the treasury (minus whatever amount was previously sent). There should also be an added variable to the struct which accounts for the amount already sent, which will allow `feesEarned` to be referenced in other logic.

**Comment by 0xToshii** [comment]
Escalate 

I believe this is a valid low-cost and simple way for a malicious user to prevent fees from processing orders in BuyOrderIssuer from being collectable by the treasury, while still getting their full order processed. As I mentioned, the only way that fees will be sent to the treasury is if `_closeOrder` is called. `_closeOrder` will not be called if `remainingOrder` != 0. This can mean something as trivial as 1 wei of USDC still being in the `remainingOrder`, when USDC is being used to purchase the dShares. This allows a malicious user to craft a transaction that fills their full buy order (in terms of `receivedAmount`) while preventing fees from going to the treasury. This can essentially block all protocol revenue from this contract, at any user's discretion. Therefore, High severity.

**Comment by sherlock-admin** [comment]
> Escalate 
> 
> I believe this is a valid low-cost and simple way for a malicious user to prevent fees from processing orders in BuyOrderIssuer from being collectable by the treasury, while still getting their full order processed. As I mentioned, the only way that fees will be sent to the treasury is if `_closeOrder` is called. `_closeOrder` will not be called if `remainingOrder` != 0. This can mean something as trivial as 1 wei of USDC still being in the `remainingOrder`, when USDC is being used to purchase the dShares. This allows a malicious user to craft a transaction that fills their full buy order (in terms of `receivedAmount`) while preventing fees from going to the treasury. This can essentially block all protocol revenue from this contract, at any user's discretion. Therefore, High severity.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by jaketimothy** [comment]
I don't see that there is a risk that the order will get locked or the protocol will not get fees. Operator can always call cancel to refund remaining order and collect fees. In the scenario described, remainingOrder > 0 so the operator could also fill the remaining order to close the order and collect fees.

I do find it useful that @0xToshii pointed out we are sending partial fills directly to user for buys, but not for sells. I will want to change that to be symmetric, but I believe the issue as described - `that a malicious user can craft a buy order which will never be complete (so fees won't be sent to the treasury)` - is invalid.

**Comment by 0xToshii** [comment]
This is a valid point - considering Operator has power to unilaterally cancel orders, they can effectively force collect fees. However, since there is overhead to this collection in terms of gas, I still suggest making the changes as I have laid out. 

Another way to restate this issue is that any user is effectively able to offload the gas cost of canceling their order (to refund `remainingOrder`) onto the Operator, as the Operator must cancel the order in order to collect fees. Protocol is still impacted by this imo

**Comment by ctf-sec** [comment]
> Another way to restate this issue is that any user is effectively able to offload the gas cost of canceling their order (to refund remainingOrder) onto the Operator, as the Operator must cancel the order in order to collect fees. Protocol is still impacted by this imo

The protocol has to pay the gas to fill the order (or cancel the order) and collect anyway as long as transaction does not keep reverting.

------ 

escalation is one things, fix is another

@jaketimothy 

In the current design, if there are a lot of orders, the operator does have to pay a lot of gas fee (if it keep reverting it getting worth, even not reverting the gas fee are paid)

GMX also let executor execute the order, but the user needs to pay the execution fee

https://gmxio.gitbook.io/gmx/trading#execution-fee

or maybe the protocol can charge higher fee in the OrderFee contract 👍

**Comment by Oot2k** [comment]
I think @jaketimothy described it well, impact is more low/informational

**Comment by 0xToshii** [comment]
Appreciate the comments. Final thoughts on this one:

1. Assuming normal flow for this contract, users will create orders which will generally leave the contract with a small amount of `remainingOrder`. At this point, users (malicious or not) are not incentivized to clear the order because of the gas fees. At this point, the treasury will not receive any fees as I have written before.
2. Now, to solve this as @jaketimothy has mentioned, requires that the protocol then starts to unilaterally cancel orders. It's clear that this was not intended to be part of the design, and would require setting up some service which handles this logic.
3. However, the issue with this solution is that now the protocol is required to pay the gas required to execute these cancel txs for nearly all buy orders, else they will receive no fees. This is clearly a loss of funds for the protocol, and regardless of how cheap the gas is, with enough volume (as this system is designed to handle), there will be a material amount of lost revenue for the protocol.

I think there's fundamentally an issue w the economic design of how fees are paid for this contract, and so I believe this should be moved to Medium.

**Comment by talllo** [comment]
dupe of #22 i believe. I think its a medium since it forces the operator to either take an unfavorable trade to complete the order or cancel the order and pay a gas fee. both fall into the realm of a "state where a material amount of funds can be lost" 
![image](https://github.com/sherlock-audit/2023-06-dinari-judging/assets/46828872/e66a35af-26c3-426c-98f8-d21083402c34)

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Based on the discussion above, 
Paying extra gas to cancel an order to avoid having the above issue is not a valid medium.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xtoshii](https://github.com/sherlock-audit/2023-06-dinari-judging/issues/78/#issuecomment-1631856184): rejected
